# After editing this file run npm run typegen to regenerate the types
name = "logbook"
pages_build_output_dir = "public"
compatibility_date = "2023-12-31"
send_metrics = true 

# This is used by wrangler to figure out which is preview and which isn't
[[d1_databases]]
binding = "DB"
database_id = "c90bea7f-6491-4a29-981f-d167093007d4"
preview_database_id = "54fd0e8d-94ae-4051-8b13-3319c31630db"
database_name = "logbook-prod"
migrations_table = "migrations"
migrations_dir = "migrations"

# Applies to both the local and the preview environments (but not the production environment) - ie PR previews etc. Normally when developing locally though you are using a local db
[[env.preview.d1_databases]]
database_id = "54fd0e8d-94ae-4051-8b13-3319c31630db"
binding = "DB"
database_name = "logbook-preview"
migrations_table = "migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"

# Apply only to the production environment
[[env.production.d1_databases]]
database_id = "c90bea7f-6491-4a29-981f-d167093007d4"
binding = "DB"
database_name = "logbook-prod"
migrations_table = "migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"